name: internship
description: Test task for internship
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  freezed_annotation: ^2.4.1

  #This is platform dependency to Mock
  package_info_plus: ^4.1.0
  json_annotation: ^4.8.1
  auto_route: ^7.4.0
  get_it: ^7.6.4
  injectable: ^2.1.1
  flutter_bloc: ^8.1.3
  retrofit: ^4.0.2
  dio: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  freezed: ^2.3.1
  json_serializable: ^6.7.1
  auto_route_generator: ^7.1.1
  injectable_generator: ^2.4.0
  retrofit_generator: ^8.0.0


flutter:

  uses-material-design: true
